# Introduction to Neural Prediction

#### A simple neural network

An empty network

In [1]:
weight = 0.1
def neural_network(input,weight):
    prediction = input*weight
    return prediction

We can use this network to make a prediciton

In [2]:
number_of_toes = [8.5,9.5,10,9]
input = number_of_toes[0]
pred = neural_network(input,weight)
print(pred)

0.8500000000000001


##### Making a prediction with multiple outputs

In [3]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i]*b[i]
    return output

weights = [0.1, 0.2, 0] 

def neural_network(input,weights):
    prediction = w_sum(input,weights)
    return prediction

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input,weights)
print(pred)

0.9800000000000001


#### Let's do the same thing with numpy so that we can take advantage of vector properties

In [4]:
import numpy as np
weights = np.array([0.1,0.2,0])

def nerual_network(input,weights):
        prediction = input.dot(weights)
        return prediciton

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input,weights)
print(pred)

0.9800000000000001


#### We can do a multiple outputs given a single input source

In [5]:
import numpy as np

def ele_mul(number,vector):
    output = [0,0,0]
    assert(len(output)==len(vector))
    for i in range(0,len(output)):
        output[i] = number*vector[i]
    return output

weights = [0.3, 0.2, 0.9] 

def neural_network(input,weights):
    pred = ele_mul(input,weights)
    return pred

wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input,weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


In [6]:
weights = [ [0.1, 0.1, -0.3], #hurt?
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ] #sad?


def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output

def neural_network(input,weights):
    pred = vect_mat_mul(input,weights)
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


##### Predicting on prediction

In [7]:
ih_wgt = [ [0.1, 0.2, -0.1], #hid[0]
           [-0.1,0.1, 0.9], #hid[1]
           [0.1, 0.4, 0.1] ] #hid[2]

           #hid[0] hid[1] hid[2]
hp_wgt = [ [0.3, 1.1, -0.3], #hurt?
           [0.1, 0.2, 0.0], #win?
           [0.0, 1.3, 0.1] ] #sad?
weights = [ih_wgt,hp_wgt]

def neural_network(input,weights):
    hid = vect_mat_mul(input,weights[0])
    pred = vect_mat_mul(hid,weights[1])
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

print(pred)


[0.21350000000000002, 0.14500000000000002, 0.5065]


#### The better way to do this using NumPy

In [26]:
import numpy as np

ih_wgt = np.array([ [0.1, 0.2, -0.1],
           [-0.1,0.1, 0.9], 
           [0.1, 0.4, 0.1]]).T

hp_wgt = np.array([[0.3, 1.1, -0.3],
           [0.1, 0.2, 0.0], 
           [0.0, 1.3, 0.1]] ).T

weights = [ih_wgt,hp_wgt]

def neural_network(input,weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)

print(pred)


[0.2135 0.145  0.5065]


##### A quick primer on numpy

In [34]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.array([[1,2,3],
            [4,5,6]])

d= np.zeros((2,3))

e = np.random.rand(2,5)
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.55181445 0.88454815 0.41402867 0.75424862 0.44993509]
 [0.87941737 0.93941904 0.05421207 0.97050514 0.68089992]]


In [40]:
print(a*0.1) # multiplies evey element in a with 0.1

print(c*0.2) # multiplies every element in c with 0.2

print(a * b) # element wise operation between a and b

print(a * b *0.2) # element wise operation between a and b then multiplication of the result to 0.2

print(a * c) # the number of since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"



[0.1 0.2 0.3]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]
[ 4 10 18]
[0.8 2.  3.6]
[[ 1  4  9]
 [ 4 10 18]]


In [41]:
print(a * e) # the number of column in this case is not equal so this will end up in a value error

ValueError: operands could not be broadcast together with shapes (3,) (2,5) 

In [48]:
a = np.zeros((2,4))
b = np.zeros((4,3))

c = a.dot(b)
print(c.shape)

e = np.zeros((2,1))
f = np.zeros((1,3))

g = e.dot(f)
print(g.shape)

h = np.zeros((5,4)).T
i = np.zeros((5,6))
j = h.dot(i)

print(j.shape)



(2, 3)
(2, 3)
(4, 6)


In [49]:
h = np.zeros((5,4))
i = np.zeros((5,6))
j = h.dot(i)

print(j.shape)

ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)